// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCVh4OWJxPQSDjhmI9a5pXe8rTewcFxxQ',
    appId: '1:123155234440:web:72c4a83980f0d6c227293d',
    messagingSenderId: '123155234440',
    projectId: 'clouad-messaging',
    authDomain: 'clouad-messaging.firebaseapp.com',
    storageBucket: 'clouad-messaging.appspot.com',
    measurementId: 'G-FRTB67NDED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIhdJkaJAAv7j855PbhV0zHlajeNDU83E',
    appId: '1:123155234440:android:b1388572ca60378627293d',
    messagingSenderId: '123155234440',
    projectId: 'clouad-messaging',
    storageBucket: 'clouad-messaging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBswK0hW9ABUATzUw_cnEN4DrmX83s17yc',
    appId: '1:123155234440:ios:06ccde41065a15d227293d',
    messagingSenderId: '123155234440',
    projectId: 'clouad-messaging',
    storageBucket: 'clouad-messaging.appspot.com',
    iosClientId: '123155234440-00lhllcaapar0dt5e7nfa67846ne6t3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.sqfliteDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBswK0hW9ABUATzUw_cnEN4DrmX83s17yc',
    appId: '1:123155234440:ios:b6c8a971a7f4defd27293d',
    messagingSenderId: '123155234440',
    projectId: 'clouad-messaging',
    storageBucket: 'clouad-messaging.appspot.com',
    iosClientId: '123155234440-6lli7fqlmft1nm0qa77eklu97s07u9k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sqfliteDemo.RunnerTests',
  );
}
